MZJ\YabBundle\Entity\Comment:
    type: entity
    table: null
    repositoryClass: MZJ\YabBundle\Entity\CommentRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        content:
            type: text
        likes:
            type: integer
        dislikes:
            type: integer
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        post:
            targetEntity: Post
            inversedBy: comments
    lifecycleCallbacks: {  }
