MZJ\YabBundle\Entity\Comment:
    type: entity
    table: comment    
    gedmo:
        tree:
           type: nested
    repositoryClass: MZJ\YabBundle\Repository\CommentRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        content:
            type: text
        likes:
            type: integer
        dislikes:
            type: integer
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: update
        lft:
            type: integer
            gedmo:
              - treeLeft
        rgt:
            type: integer
            gedmo:
              - treeRight
        lvl:
            type: integer
            gedmo:
              - treeLevel
        root:
            type: integer
            gedmo:
              - treeRoot
    manyToOne:
        post:
            targetEntity: Post
            inversedBy: comments
        parent:
           targetEntity: MZJ\YabBundle\Entity\Comment
           inversedBy: children
           joinColumn:
               name: parent_id
               referencedColumnName: id
               onDelete: SET NULL
           gedmo:
               - treeParent
    oneToMany:
        children:
            targetEntity: MZJ\YabBundle\Entity\Comment
            mappedBy: parent
            orderBy:
                id: DESC
    lifecycleCallbacks: {  }
