MZJ\YabBundle\Entity\Post:
    type: entity
    table: null
    repositoryClass: MZJ\YabBundle\Repository\PostRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        title:
            type: string
            length: 255
        content:
            type: text
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: update
        slug:
            type: string
            length: 128
            unique: true
            gedmo:
                slug:
                    style: camel
                    fields:
                        - title
                        - id
    lifecycleCallbacks: { }
