<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120811174044 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE comment ADD parent_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE comment ADD CONSTRAINT FK_9474526C727ACA70 FOREIGN KEY (parent_id) REFERENCES comment (id) ON DELETE SET NULL");
        $this->addSql("CREATE INDEX IDX_9474526C727ACA70 ON comment (parent_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE comment DROP FOREIGN KEY FK_9474526C727ACA70");
        $this->addSql("DROP INDEX IDX_9474526C727ACA70 ON comment");
        $this->addSql("ALTER TABLE comment DROP parent_id");
    }
}
