post:
    pattern:  /
    defaults: { _controller: "MZJYabBundle:Post:index" }

post_show:
    pattern:  /{created}/{id}/{slug}
    defaults: { _controller: "MZJYabBundle:Post:show" }
    requirements:
        _method:  GET
        id: \d+
        
post_new:
    pattern:  /new
    defaults: { _controller: "MZJYabBundle:Post:new" }

post_create:
    pattern:  /create
    defaults: { _controller: "MZJYabBundle:Post:create" }
    requirements: { _method: post }

post_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "MZJYabBundle:Post:edit" }

post_update:
    pattern:  /{id}/update
    defaults: { _controller: "MZJYabBundle:Post:update" }
    requirements: { _method: post }

post_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "MZJYabBundle:Post:delete" }
    requirements: { _method: post }
