MZJYabBundle_home:
    pattern:  /
    defaults: { _controller: MZJYabBundle:Blog:index }

MZJYabBundle_post_view:
    pattern:  /{id}/{slug}
    defaults: { _controller: "MZJYabBundle:Post:view" }
    requirements:
        _method:  GET
        id: \d+
        
MZJYabBundle_comments:
    pattern:  /comment/{postId)
    defaults: { _controller: "MZJYabBundle:Comment:comments" }
    requirements:
        _method:  GET
        id: \d+
        
                
# Includes         
MZJYabBundle_post:
    resource: "@MZJYabBundle/Resources/config/routing/post.yml"
    prefix:   /post
    
MZJYabBundle_comment:
    resource: "@MZJYabBundle/Resources/config/routing/comment.yml"
    prefix:   /comment
 
MZJYabBundle_category:
    resource: "@MZJYabBundle/Resources/config/routing/category.yml"
    prefix:   /category
