MZJYabBundle_post:
    resource: "@MZJYabBundle/Resources/config/routing/post.yml"
    prefix:   /post
    
MZJYabBundle_comment:
    resource: "@MZJYabBundle/Resources/config/routing/comment.yml"
    prefix:   /comment
 
MZJYabBundle_category:
    resource: "@MZJYabBundle/Resources/config/routing/category.yml"
    prefix:   /category

MZJYabBundle_tag:
        resource: "@MZJYabBundle/Resources/config/routing/tag.yml"
        prefix:   /tag
        
MZJYabBundle_home:
    pattern:  /
    defaults: { _controller: MZJYabBundle:Blog:index }
