# Homepage - Lists all posts
MZJYabBundle_home:
    pattern:  /
    defaults: { _controller: MZJYabBundle:Blog:index }

# Post view
MZJYabBundle_post_view:
    pattern:  /{id}/{slug}
    defaults: { _controller: "MZJYabBundle:Post:view" }
    requirements:
        _method:  GET
        id: \d+
        
# Lists posts under category     
MZJYabBundle_posts_by_category:
    pattern:  /category/{id}/{slug}
    defaults: { _controller: "MZJYabBundle:Post:inCategory" }
    requirements:
        _method:  GET
        id: \d+
        
# Lists posts with specified tag       
MZJYabBundle_posts_by_tag:
    pattern:  /tag/{tag}
    defaults: { _controller: "MZJYabBundle:Post:withTag" }
    requirements:
        _method:  GET
 
# Classic search        
MZJYabBundle_posts_by_term:
    pattern:  /search/{term}
    defaults: { _controller: "MZJYabBundle:Blog:search" }
    requirements:
        _method:  GET
        id: \d+
        
        
################################    
#   Includes                   #
################################
MZJYabBundle_post:
    resource: "@MZJYabBundle/Resources/config/routing/post.yml"
    prefix:   /post
    
MZJYabBundle_comment:
    resource: "@MZJYabBundle/Resources/config/routing/comment.yml"
    prefix:   /comment
 
MZJYabBundle_category:
    resource: "@MZJYabBundle/Resources/config/routing/category.yml"
    prefix:   /category
