parameters:
#    mzj_yab.example.class: MZJ\YabBundle\Example

services:
    mzj_yab.twig.extension:
        class: MZJ\YabBundle\Twig\Extension\RepeatExtension
        tags:
            - { name: twig.extension }
