parameters:
#    mzj_yab.example.class: MZJ\YabBundle\Example
    fpn_tag.tag_manager.class: FPN\TagBundle\Entity\TagManager

services:
    mzj_yab.twig.extension:
        class: MZJ\YabBundle\Twig\Extension\RepeatExtension
        tags:
            - { name: twig.extension }
            
            
    my_logging_pointcut:
        class: MZJ\YabBundle\Service\LoggingPointcut
        arguments: ["@annotation_reader"]
        tags:
            - { name: jms_aop.pointcut, interceptor: logging_interceptor }
            
 
    logging_interceptor:
        class: MZJ\YabBundle\Interceptor\LoggingInterceptor
        arguments: ["@security.context", "@logger"]